// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26S9CoGOvFK9spMeumy_vd-nU74LTYb8',
    appId: '1:946102809592:web:3f8206707ffb4b09f49c0d',
    messagingSenderId: '946102809592',
    projectId: 'barlow-bd0cc',
    authDomain: 'barlow-bd0cc.firebaseapp.com',
    storageBucket: 'barlow-bd0cc.firebasestorage.app',
    measurementId: 'G-5RVR769G7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo-qouTrJnLBSW-wtRlfiz9iNTbcL4e5c',
    appId: '1:946102809592:android:aabb91e228915c36f49c0d',
    messagingSenderId: '946102809592',
    projectId: 'barlow-bd0cc',
    storageBucket: 'barlow-bd0cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB9jk-JfSerHCOFCY_ZrOFx0YkNLoLnig',
    appId: '1:946102809592:ios:ed72cb03107ba033f49c0d',
    messagingSenderId: '946102809592',
    projectId: 'barlow-bd0cc',
    storageBucket: 'barlow-bd0cc.firebasestorage.app',
    iosBundleId: 'com.barlow.front',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB9jk-JfSerHCOFCY_ZrOFx0YkNLoLnig',
    appId: '1:946102809592:ios:ed72cb03107ba033f49c0d',
    messagingSenderId: '946102809592',
    projectId: 'barlow-bd0cc',
    storageBucket: 'barlow-bd0cc.firebasestorage.app',
    iosBundleId: 'com.barlow.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB26S9CoGOvFK9spMeumy_vd-nU74LTYb8',
    appId: '1:946102809592:web:bddfbbe8e080475ef49c0d',
    messagingSenderId: '946102809592',
    projectId: 'barlow-bd0cc',
    authDomain: 'barlow-bd0cc.firebaseapp.com',
    storageBucket: 'barlow-bd0cc.firebasestorage.app',
    measurementId: 'G-PTGQQ89TLQ',
  );
}
